export type Row = {id:number; [key:string]:unknown};
export type Field = {key:string;label:string;type?:string;required?:boolean;options?:[string,string][];resource?:string;hint?:string};
export type Resource = {title:string;singular:string;description:string;columns:[string,string][];fields:Field[];filter?:Field};
const text=(key:string,label:string,required=false):Field=>({key,label,required});
const num=(key:string,label:string,required=false):Field=>({key,label,type:'number',required});
const day=(key:string,label:string,required=false):Field=>({key,label,type:'date',required});
const area=(key:string,label:string,required=false):Field=>({key,label,type:'textarea',required});
const rel=(key:string,label:string,resource:string,required=false):Field=>({key,label,resource,required});
const select=(key:string,label:string,options:[string,string][]):Field=>({key,label,options});
export const statuses:[string,string][]=[['unknown','Por verificar'],['operational','Operativo'],['maintenance','En mantenimiento'],['failed','Fuera de servicio'],['retired','Baja']];
export const orderStatuses:[string,string][]=[['open','Abierta'],['scheduled','Programada'],['in_progress','En proceso'],['completed','Completada'],['cancelled','Cancelada']];
const review:Field={key:'needs_review',label:'Pendiente de revisión',type:'checkbox'};
export const resources:Record<string,Resource>={
 assets:{title:'Inventario de equipos',singular:'equipo',description:'Cada componente, su ubicación y su historia, en un solo lugar.',columns:[['code','Código'],['location_name','Ubicación'],['brand','Marca'],['model_code','Modelo'],['status','Estado'],['next_maintenance','Próx. servicio']],filter:select('status','Todos los estados',statuses),fields:[text('code','Código de equipo',true),rel('location','Ubicación','locations'),rel('model','Modelo técnico','models'),text('serial_number','Número de serie'),select('status','Estado',statuses),select('criticality','Criticidad',[['low','Baja'],['medium','Media'],['high','Alta']]),rel('supplier','Proveedor','suppliers'),day('acquired_on','Fecha de adquisición'),day('installed_on','Fecha de instalación'),day('warranty_until','Fin de garantía'),num('purchase_cost','Costo de adquisición (MXN)'),num('maintenance_interval_days','Intervalo preventivo (días)',true),day('next_maintenance','Próximo mantenimiento'),review,area('notes','Observaciones')]},
 'work-orders':{title:'Órdenes de trabajo',singular:'orden de trabajo',description:'Programa, asigna y documenta cada intervención.',columns:[['id','Orden'],['asset_code','Equipo'],['title','Trabajo'],['scheduled_on','Programada'],['technician','Responsable'],['status','Estado']],filter:select('status','Todos los estados',orderStatuses),fields:[rel('asset','Equipo','assets',true),text('title','Trabajo a realizar',true),select('kind','Tipo',[['preventive','Preventivo'],['corrective','Correctivo'],['installation','Instalación'],['inspection','Inspección']]),select('priority','Prioridad',[['low','Baja'],['medium','Media'],['high','Alta'],['urgent','Urgente']]),select('status','Estado',orderStatuses),day('scheduled_on','Fecha programada',true),text('technician','Técnico responsable'),rel('supplier','Proveedor externo','suppliers'),area('diagnosis','Diagnóstico'),{key:'checklist',label:'Lista de verificación',type:'checklist'},area('resolution','Trabajo realizado'),day('completed_on','Fecha de terminación'),num('cost','Costo real (MXN)')]},
 models:{title:'Biblioteca técnica',singular:'modelo',description:'Especificaciones compartidas, manuales y datos de placa.',columns:[['code','Código'],['brand','Marca'],['indoor_model','Evaporadora'],['capacity_btu','Capacidad BTU/h'],['inverter','Inverter'],['needs_review','Revisión']],fields:[text('code','Código del modelo',true),text('brand','Marca',true),text('indoor_model','Modelo de evaporadora'),text('outdoor_model','Modelo de condensadora'),num('capacity_btu','Capacidad BTU/h'),select('inverter','Tecnología inverter',[['true','Sí'],['false','No']]),text('equipment_type','Tipo de equipo'),text('refrigerant','Refrigerante'),text('voltage','Voltaje'),num('rated_power_kw','Potencia nominal (kW)'),{key:'manual_url',label:'URL del manual',type:'url'},review,area('notes','Notas técnicas')]},
 locations:{title:'Ubicaciones',singular:'ubicación',description:'Un directorio de espacios para todo el campus.',columns:[['code','Código'],['building','Edificio'],['level','Área / nivel'],['position','Posición'],['name','Espacio']],fields:[text('code','Código',true),text('name','Nombre del espacio',true),text('building','Edificio'),text('level','Área / nivel'),text('position','Posición'),review,area('notes','Observaciones')]},
 acquisitions:{title:'Adquisiciones',singular:'adquisición',description:'De la solicitud a la recepción: presupuesto y trazabilidad.',columns:[['reference','Referencia'],['supplier_name','Proveedor'],['quantity','Cantidad'],['unit_cost','Precio unitario'],['expected_on','Entrega prevista'],['status','Estado']],filter:select('status','Todos los estados',[['requested','Solicitada'],['approved','Aprobada'],['ordered','En compra'],['received','Recibida'],['cancelled','Cancelada']]),fields:[text('reference','Referencia de compra',true),rel('supplier','Proveedor','suppliers'),rel('model','Modelo','models'),rel('location','Destino','locations'),num('quantity','Cantidad de sistemas',true),num('unit_cost','Precio unitario (MXN)',true),day('requested_on','Fecha de solicitud',true),day('expected_on','Entrega prevista'),select('status','Estado',[['requested','Solicitada'],['approved','Aprobada'],['ordered','En compra'],['received','Recibida'],['cancelled','Cancelada']]),text('invoice','Factura / documento'),area('justification','Justificación',true),area('notes','Notas (incluye códigos de equipos recibidos)')]},
 suppliers:{title:'Proveedores',singular:'proveedor',description:'Contactos para compra, servicio y soporte.',columns:[['name','Proveedor'],['contact','Contacto'],['phone','Teléfono'],['email','Correo'],['tax_id','RFC']],fields:[text('name','Razón social / nombre',true),text('contact','Contacto'),text('phone','Teléfono'),{key:'email',label:'Correo',type:'email'},text('tax_id','RFC'),area('notes','Notas')]},
 sources:{title:'Revisión de datos',singular:'revisión',description:'Comprueba las excepciones y el histórico con el documento original.',columns:[['category','Origen'],['legacy_id','Referencia'],['page','Página'],['status','Estado'],['review_note','Resolución']],filter:select('status','Todos los estados',[['pending','Pendiente'],['verified','Verificado'],['duplicate','Duplicado']]),fields:[select('status','Resultado de revisión',[['pending','Pendiente'],['verified','Verificado'],['duplicate','Duplicado']]),area('review_note','Evidencia y acciones realizadas',true)]},
 historical:{title:'Histórico de servicios',singular:'registro histórico',description:'90 intervenciones transcritas; la fila 91 es un total y no un servicio adicional.',columns:[['legacy_id','Registro original'],['asset_code','Equipo'],['description','Concepto'],['performed_on','Fecha'],['recorded_cost','Costo literal'],['possible_duplicate_of','Posible repetido de']],fields:[text('asset_code','Equipo'),text('work_code','Concepto'),area('description','Descripción'),day('performed_on','Fecha del trabajo'),num('recorded_cost','Costo literal (moneda no indicada)'),num('possible_duplicate_of','Posible repetición del registro')]},
 audit:{title:'Bitácora de actividad',singular:'evento',description:'Trazabilidad de cambios realizados en la plataforma.',columns:[['at','Fecha'],['actor_name','Usuario'],['action','Acción'],['resource','Módulo'],['object_id','Registro']],fields:[]}
};
export const labels:Record<string,string>=Object.fromEntries([...statuses,...orderStatuses,['preventive','Preventivo'],['corrective','Correctivo'],['installation','Instalación'],['inspection','Inspección'],['low','Baja'],['medium','Media'],['high','Alta'],['urgent','Urgente'],['requested','Solicitada'],['approved','Aprobada'],['ordered','En compra'],['received','Recibida'],['pending','Pendiente'],['verified','Verificado'],['duplicate','Duplicado'],['historical','Trabajos históricos'],['requests','Solicitudes históricas'],['summary','Resumen histórico'],['create','Alta'],['update','Actualización'],['import','Importación']]);
