'use client';
import {useState,useEffect,useRef,FormEvent} from 'react';
import {LayoutDashboard,Wind,Wrench,MapPin,BookOpen,ShoppingCart,Truck,FileBarChart,ClipboardCheck,History,Search,Plus,ArrowUpRight,ArrowRight,ChevronLeft,ChevronRight,CalendarDays,LogOut,Menu,X,Check,AlertTriangle,Download,Printer,ShieldCheck,Activity,Building2,ChevronDown,LoaderCircle,ExternalLink} from 'lucide-react';
import {api} from './api';
import {MaintenanceEntry,loadMaintenance,filterMaintenance} from './maintenance';
import {resources,Row,Field,labels} from './resources';
type User={id:number;username:string;name:string;role:string;can_manage_users?:boolean};
type Dashboard={assets:number;locations:number;models:number;operational:number;unknown:number;failed:number;overdue:number;unscheduled:number;open_orders:number;pending_review:number;maintenance_cost:number;cost_records:number;warranty_expiring:number;by_building:{location__building:string|null;total:number}[];by_brand:{model__brand:string|null;total:number}[];upcoming:Row[];recent:Row[]};
const menu=[{id:'dashboard',label:'Vista general',icon:LayoutDashboard},{id:'assets',label:'Inventario',icon:Wind},{id:'work-orders',label:'Mantenimiento',icon:Wrench},{id:'agenda',label:'Agenda de servicios',icon:CalendarDays},{id:'locations',label:'Ubicaciones',icon:MapPin},{id:'models',label:'Biblioteca técnica',icon:BookOpen},{id:'acquisitions',label:'Adquisiciones',icon:ShoppingCart},{id:'suppliers',label:'Proveedores',icon:Truck},{id:'reports',label:'Reportes',icon:FileBarChart},{id:'sources',label:'Revisión de datos',icon:ClipboardCheck},{id:'historical',label:'Histórico importado',icon:History},{id:'audit',label:'Bitácora',icon:History}];
const money=(v:unknown)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(Number(v||0));
const display=(v:unknown,k=''):string=>{if(v===null||v===undefined||v==='')return 'Sin registrar';if(typeof v==='boolean')return v?'Sí':'No';if(k==='unit_cost'||k==='purchase_cost'||k==='cost')return money(v);if(typeof v==='object')return JSON.stringify(v);if(k==='at'||k==='created_at'||k==='updated_at')return new Date(String(v)).toLocaleString('es-MX');return labels[String(v)]||String(v);};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function Badge({value}:{value:unknown}){const s=String(value);return <span className={`pill ${['operational','completed','verified','received'].includes(s)?'good':['failed','urgent','high'].includes(s)?'bad':['unknown','pending','open','maintenance','in_progress','requested','scheduled'].includes(s)?'warn':'neutral'}`}><i/>{display(value)}</span>;}
function Loading(){return <div className="empty"><LoaderCircle className="spin" size={28}/><p>Cargando información…</p></div>;}
function ErrorBox({message}:{message:string}){return <p className="alert-error" role="alert">{message}</p>;}
function Empty({title,description}:{title:string;description?:string}){return <div className="empty"><ClipboardCheck size={32}/><h3>{title}</h3><p>{description||'Los registros aparecerán aquí cuando se capturen.'}</p></div>;}

export default function Workspace(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[section,setSection]=useState('dashboard'),[mobile,setMobile]=useState(false),[globalError,setGlobalError]=useState('');
 useEffect(()=>{api('me/').then(setUser).catch(()=>{}).finally(()=>setLoading(false));const hash=location.hash.slice(1);if(hash==='account'||menu.some(m=>m.id===hash))setSection(hash);},[]);
 function navigate(s:string){setSection(s);location.hash=s;setMobile(false);}
 async function exit(){try{await api('logout/',{method:'POST'});setUser(null);}catch(e){setGlobalError((e as Error).message);}}
 if(loading)return <div className="boot"><Wind size={40}/><Loading/></div>;
 if(!user)return <Login onLogin={setUser}/>;
 return <div className="app-shell">
  {mobile&&<button className="scrim" aria-label="Cerrar menú" onClick={()=>setMobile(false)}/>}
  <aside className={`sidebar ${mobile?'open':''}`}>
   <a className="brand-lockup" href="#dashboard" onClick={()=>navigate('dashboard')}><img src="/Modelo.jpg" width="44" height="44" alt="Escuela Modelo"/><div><span>ESCUELA MODELO</span><strong>Modelo AC<span className="brand-dot">.</span></strong></div></a>
   <div className="workspace-label"><span className="online-dot"/> Gestión de climatización</div>
   <p className="nav-caption">ESPACIO DE TRABAJO</p>
   <nav aria-label="Navegación principal">{menu.map((item,i)=><div key={item.id}>{i===8&&<p className="nav-caption second">CONTROL Y ANÁLISIS</p>}<button className={`nav-item ${section===item.id?'active':''}`} onClick={()=>navigate(item.id)} aria-current={section===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span>{section===item.id&&<span className="active-dot"/>}</button></div>)}</nav>
   <div className="sidebar-bottom"><div className="avatar">{user.name.slice(0,2).toUpperCase()}</div><div><button className="account-link" onClick={()=>navigate('account')} title="Mi cuenta">{user.name}</button><span>{user.role}</span></div><button onClick={exit} title="Cerrar sesión" aria-label="Cerrar sesión"><LogOut size={18}/></button></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="Abrir menú" onClick={()=>setMobile(true)}><Menu size={22}/></button><span>Escuela Modelo</span><ChevronRight size={14}/><strong>{menu.find(m=>m.id===section)?.label||(section==='account'?'Mi cuenta':'')}</strong></div><div className="topbar-right"><span className="institution-tag"><ShieldCheck size={14}/> Portal institucional</span><span className="date-label">{new Date().toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}</span></div></header>
   <main className="main-content" id="main-content">
    {globalError&&<ErrorBox message={globalError}/>}
    {section==='account'?<Account user={user}/>:section==='dashboard'?<Overview navigate={navigate}/>:section==='reports'?<Reports/>:section==='agenda'?<Agenda user={user}/>:section==='work-orders'?<MaintenanceView user={user}/>:<ResourceView key={section} resource={section} user={user}/>}
    <footer className="footer"><span>Escuela Modelo · Gestión de infraestructura</span><span>Modelo AC / 1.0</span></footer>
   </main>
  </div>
 </div>;
}
function Login({onLogin}:{onLogin:(u:User)=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{onLogin(await api('login/',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password')})}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="login-shell"><div className="login-story"><div className="brand-lockup"><img src="/Modelo.jpg" width="54" height="54" alt="Escuela Modelo"/><div><span>ESCUELA MODELO</span><strong>Modelo AC.</strong></div></div><div><span className="story-eyebrow">CUIDAMOS CADA ESPACIO</span><h1>Un mejor ambiente<br/>para aprender.</h1><p>El control de la climatización de Escuela Modelo: equipos, mantenimiento y decisiones en un mismo lugar.</p><div className="story-icons"><span><Wind/>Inventario</span><span><Wrench/>Mantenimiento</span><span><Activity/>Control</span></div></div><small>Infraestructura que acompaña a nuestra comunidad.</small></div><section className="login-card"><span className="section-eyebrow">ACCESO INSTITUCIONAL</span><h2>Bienvenido de nuevo</h2><p className="muted">Ingresa con tu cuenta para continuar.</p><form onSubmit={submit} className="form-stack"><label className="field-label">Usuario<input className="field-input" name="username" autoComplete="username" required autoFocus/></label><label className="field-label">Contraseña<input className="field-input" name="password" type="password" autoComplete="current-password" required/></label>{error&&<ErrorBox message={error}/>}<button className="primary-button" disabled={busy}>{busy?'Validando…':'Entrar a Modelo AC'}<ArrowRight size={17}/></button></form><div className="login-note"><ShieldCheck size={18}/><span>Acceso reservado al personal autorizado.<br/>Solicita tu cuenta al administrador.</span></div></section></main>;
}
function Overview({navigate}:{navigate:(s:string)=>void}){
 const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState('');
 useEffect(()=>{api('dashboard/').then(setData).catch(e=>setError(e.message));},[]);
 if(error)return <ErrorBox message={error}/>;if(!data)return <Loading/>;
 const cards=[{title:'Componentes registrados',value:data.assets,sub:`${data.models} modelos en catálogo`,icon:Wind,color:'blue'},{title:'Órdenes abiertas',value:data.open_orders,sub:'Servicios por atender',icon:Wrench,color:'orange'},{title:'Mantenimiento vencido',value:data.overdue,sub:`${data.unscheduled} sin programación`,icon:CalendarDays,color:'red'},{title:'Costo de mantenimiento',value:money(data.maintenance_cost),sub:`${data.cost_records} órdenes cerradas con costo`,icon:Activity,color:'green'}];
 return <><div className="page-heading"><div><p className="section-eyebrow">CONTROL DE CLIMATIZACIÓN</p><h1>Todo bajo control.</h1><p className="muted">Una mirada completa a los equipos y al cuidado de nuestros espacios.</p></div><button className="secondary-button" onClick={()=>navigate('reports')}><Download size={16}/> Reportes</button></div>
  <section className="hero-panel"><div><span className="hero-kicker"><span className="online-dot"/>ESCUELA MODELO</span><h2>Cuidar el ambiente.<br/>Proteger la inversión.</h2><p>Del primer registro al próximo servicio.<br/>Cada equipo cuenta con una historia.</p><button onClick={()=>navigate('assets')}>Explorar inventario <ArrowUpRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="ac-unit"><div className="ac-logo">MODELO</div><span className="ac-led"/><div className="ac-vent"/></div><div className="air-lines"><i/><i/><i/></div><div className="art-label"><Wind size={18}/><span>Gestión integral<br/><strong>Climatización del campus</strong></span></div></div></section>
  <section className="kpi-grid" aria-label="Indicadores">{cards.map(c=><div className="kpi-card" key={c.title}><div className="kpi-top"><span>{c.title}</span><div className={`kpi-icon ${c.color}`}><c.icon size={18}/></div></div><strong>{c.value}</strong><p>{c.sub}</p></div>)}</section>
  {(data.unknown>0||data.pending_review>0)&&<div className="data-notice"><div className="notice-icon"><ShieldCheck size={22}/></div><div><strong>Una base de datos con trazabilidad</strong><p>{data.unknown} componentes tienen estado operativo por verificar. Hay {data.pending_review} revisiones de origen pendientes. Las evaporadoras y condensadoras se cuentan por separado.</p></div><button onClick={()=>navigate('sources')}>Revisar datos <ArrowRight size={16}/></button></div>}
  <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="section-eyebrow">DISTRIBUCIÓN</p><h2>El campus, en cifras</h2></div><span className="small-tag">{data.locations} ubicaciones</span></div><div className="building-chart">{data.by_building.map(b=><div className="bar-row" key={b.location__building||'none'}><span>{b.location__building?`Edificio ${b.location__building.toUpperCase()}`:'Sin asignar'}</span><div className="bar-track"><div style={{width:`${b.total/Math.max(...data.by_building.map(x=>x.total),1)*100}%`}}/></div><strong>{b.total}</strong></div>)}</div><p className="chart-footnote">Distribución de componentes; no equivale al número de sistemas completos.</p></section><section className="panel"><div className="panel-heading"><div><p className="section-eyebrow">PLAN DE CUIDADO</p><h2>Próximos servicios</h2></div><button className="text-button" onClick={()=>navigate('agenda')}>Ver agenda <ArrowUpRight size={15}/></button></div>{data.upcoming.length?<div className="service-list">{data.upcoming.map(o=><div key={o.id} className="service-row"><div className="service-date"><CalendarDays size={19}/><span>{display(o.scheduled_on)}</span></div><div><strong>{display(o.title)}</strong><p>{display(o.asset_code)} · {display(o.location_name)}</p></div><Badge value={o.status}/></div>)}</div>:<Empty title="El próximo servicio empieza aquí" description="Programa las primeras órdenes para construir la agenda de mantenimiento."/>}<button className="panel-bottom-action" onClick={()=>navigate('work-orders')}>Gestionar órdenes de trabajo <ArrowRight size={16}/></button></section></div>
  <div className="quick-grid"><button onClick={()=>navigate('models')}><BookOpen/><div><strong>Conoce tus equipos</strong><span>Modelos, capacidades y manuales técnicos</span></div><ArrowUpRight/></button><button onClick={()=>navigate('acquisitions')}><ShoppingCart/><div><strong>Planea la siguiente inversión</strong><span>Adquisiciones y control de presupuesto</span></div><ArrowUpRight/></button><button onClick={()=>navigate('reports')}><FileBarChart/><div><strong>Decide con información</strong><span>Reportes de inventario, costos y garantías</span></div><ArrowUpRight/></button></div>
 </>;
}
function MaintenanceView({user}:{user:User}){
 const [entries,setEntries]=useState<MaintenanceEntry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[origin,setOrigin]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<MaintenanceEntry|null>(null),[editing,setEditing]=useState(false),[revision,setRevision]=useState(0);
 const canEdit=user.role==='Administración'||user.role==='Mantenimiento';
 useEffect(()=>{let active=true;setLoading(true);setError('');loadMaintenance(api).then(data=>{if(active)setEntries(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[revision]);
 const filtered=filterMaintenance(entries,search,origin,status),count=filtered.length,rows=filtered.slice((page-1)*50,page*50);
 const close=()=>{setSelected(null);setEditing(false);};
 return <><div className="page-heading"><div><p className="section-eyebrow">CUIDADO DE LOS EQUIPOS</p><h1>Mantenimiento</h1><p className="muted">Todos los trabajos en un solo lugar: históricos importados y órdenes de la aplicación.</p></div>{canEdit&&<button className="primary-button" onClick={()=>{setSelected(null);setEditing(true);}}><Plus size={18}/> Nueva orden de trabajo</button>}</div>
 <div className="mini-banner"><History size={18}/><p>El histórico conserva las fechas, referencias y posibles repeticiones del documento original. Selecciona «Realizados» para consultar los trabajos terminados de ambos orígenes.</p></div>
 <section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><Search size={18}/><input aria-label="Buscar mantenimientos" placeholder="Buscar equipo, trabajo o ubicación…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{search&&<button aria-label="Limpiar búsqueda" onClick={()=>{setSearch('');setPage(1);}}><X size={15}/></button>}</div><div className="toolbar-right"><select className="filter-select" aria-label="Origen del mantenimiento" value={origin} onChange={e=>{setOrigin(e.target.value);setPage(1);}}><option value="">Todos los orígenes</option><option value="historical">Histórico importado</option><option value="work-orders">Aplicación</option></select><select className="filter-select" aria-label="Estado del mantenimiento" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Todos los estados</option><option value="completed">Realizados</option><option value="open">Abiertos</option><option value="scheduled">Programados</option><option value="in_progress">En proceso</option><option value="cancelled">Cancelados</option></select><span className="record-count" aria-live="polite">{loading?'Cargando…':`${count} registros`}</span></div></div>
 {error?<ErrorBox message={error}/>:loading?<Loading/>:!rows.length?<Empty title="Sin mantenimientos para esta consulta" description="Prueba otra búsqueda o cambia el origen y el estado."/>:<div className="table-scroll"><table><thead><tr>{['Referencia','Equipo / ubicación','Trabajo','Fecha','Estado','Origen'].map(label=><th key={label}>{label}</th>)}<th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{rows.map(entry=><tr key={entry.key}><td><button className="row-link" onClick={()=>setSelected(entry)}>{entry.reference}</button></td><td><strong>{display(entry.row.asset_code)}</strong><div className="muted">{display(entry.row.location_name)}</div></td><td>{entry.title}{Boolean(entry.row.possible_duplicate_of)&&<div><span className="pill warn">Posible repetición</span></div>}</td><td>{display(entry.date)}{entry.resource==='work-orders'&&entry.status!=='completed'&&<div className="helper-text">Programada</div>}</td><td>{entry.resource==='historical'?<span className="pill good">Realizado (histórico)</span>:<Badge value={entry.status}/>}</td><td>{entry.resource==='historical'?'Histórico importado':'Aplicación'}</td><td><button className="icon-button" aria-label={`Ver mantenimiento ${entry.reference}`} onClick={()=>setSelected(entry)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>}
 <div className="pagination"><span>{count?`${(page-1)*50+1}–${Math.min(page*50,count)} de ${count}`:'0 registros'}</span><div><button className="icon-button" aria-label="Página anterior" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>Página {page}</span><button className="icon-button" aria-label="Página siguiente" disabled={page*50>=count||loading} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></div></section>
 {(selected||editing)&&<RecordDialog resource={selected?.resource||'work-orders'} row={selected?.row||null} editing={editing} canEdit={canEdit&&selected?.resource!=='historical'&&selected?.status!=='completed'} onEdit={()=>setEditing(true)} onClose={close} onSaved={()=>{close();setRevision(r=>r+1);}}/>}
 </>;
}
function ResourceView({resource,user}:{resource:string;user:User}){
 const config=resources[resource];const [rows,setRows]=useState<Row[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Row|null>(null),[editing,setEditing]=useState(false),[revision,setRevision]=useState(0);
 const canEdit=!['historical','audit'].includes(resource)&&(user.role==='Administración'||(user.role==='Mantenimiento'&&resource==='work-orders'));
 useEffect(()=>{const t=setTimeout(()=>{setQuery(search);setPage(1);},250);return()=>clearTimeout(t);},[search]);
 useEffect(()=>{let active=true;setLoading(true);setError('');const params=new URLSearchParams({page:String(page),search:query});if(filter&&config.filter)params.set(config.filter.key,filter);api(`${resource}/?${params}`).then(d=>{if(active){setRows(d.results);setCount(d.count);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[resource,page,query,filter,revision,config.filter]);
 const saved=()=>{setEditing(false);setSelected(null);setRevision(x=>x+1);};
 return <><div className="page-heading"><div><p className="section-eyebrow">GESTIÓN INSTITUCIONAL</p><h1>{config.title}</h1><p className="muted">{config.description}</p></div>{canEdit&&!['sources','audit'].includes(resource)&&<button className="primary-button" onClick={()=>{setSelected(null);setEditing(true);}}><Plus size={18}/> Nueva {config.singular==='equipo'?'alta':config.singular}</button>}</div>
 {resource==='historical'&&<div className="mini-banner"><History size={18}/><p>Los costos se muestran literalmente, sin asumir moneda ni que un cero sea un servicio gratuito. Las posibles repeticiones se conservan señaladas. Estos registros no alteran la agenda ni el gasto operativo nuevo.</p></div>}
 {resource==='assets'&&<div className="mini-banner"><Wind size={18}/><p>Inventario por componente. Los códigos <strong>ee</strong> y <strong>ec</strong> se conservan del registro original. El estado inicial es «Por verificar».</p></div>}
 {resource==='sources'&&<div className="mini-banner"><ClipboardCheck size={19}/><p>La fotografía complementa las ubicaciones 51–107. Resolver una revisión documenta la verificación; corrige el registro vinculado antes de marcarla como verificada.</p></div>}
 <section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><Search size={18}/><input aria-label="Buscar registros" placeholder="Buscar por código, nombre o referencia…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Limpiar búsqueda" onClick={()=>setSearch('')}><X size={15}/></button>}</div><div className="toolbar-right">{config.filter&&<select className="filter-select" aria-label={config.filter.label} value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="">{config.filter.label}</option>{config.filter.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}<span className="record-count">{count} registros</span></div></div>
 {error?<ErrorBox message={error}/>:loading?<Loading/>:!rows.length?<Empty title={query||filter?'Sin coincidencias':'Aún no hay registros'} description={query||filter?'Prueba otra búsqueda o cambia los filtros.':undefined}/>:<div className="table-scroll"><table><thead><tr>{config.columns.map(([key,label])=><th key={key}>{label}</th>)}<th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{config.columns.map(([key],i)=><td key={key}>{i===0?<button className="row-link" onClick={()=>{setSelected(row);setEditing(false);}}>{resource==='work-orders'?`OT-${row.id}`:display(row[key],key)}</button>:key==='status'?<Badge value={row[key]}/>:key==='needs_review'?<span className={`pill ${row[key]?'warn':'good'}`}>{row[key]?'Pendiente':'Revisado'}</span>:<span className={key==='location_name'||key==='name'?'cell-name':''}>{display(row[key],key)}</span>}</td>)}<td><button className="icon-button" aria-label={`Ver registro ${row.id}`} onClick={()=>{setSelected(row);setEditing(false);}}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>}
 <div className="pagination"><span>{count?`${(page-1)*50+1}–${Math.min(page*50,count)} de ${count}`:'0 registros'}</span><div><button className="icon-button" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)} aria-label="Página anterior"><ChevronLeft size={18}/></button><span>Página {page}</span><button className="icon-button" disabled={page*50>=count||loading} onClick={()=>setPage(p=>p+1)} aria-label="Página siguiente"><ChevronRight size={18}/></button></div></div></section>
 {(selected||editing)&&<RecordDialog resource={resource} row={selected} editing={editing} canEdit={canEdit&&!(resource==='work-orders'&&selected?.status==='completed')} onEdit={()=>setEditing(true)} onClose={()=>{setSelected(null);setEditing(false);}} onSaved={saved}/>}
 </>;
}
function RecordDialog({resource,row,editing,canEdit,onEdit,onClose,onSaved}:{resource:string;row:Row|null;editing:boolean;canEdit:boolean;onEdit:()=>void;onClose:()=>void;onSaved:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const config=resources[resource];
 useEffect(()=>{dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[]);
 return <dialog ref={dialog} className="record-dialog" onCancel={onClose}><div className="dialog-header"><div><p className="section-eyebrow">{config.title}</p><h2>{editing?(row?'Editar registro':`Nueva alta · ${config.singular}`):display(row?.code||row?.reference||row?.name||row?.title||`Registro ${row?.id}`)}</h2></div><button className="icon-button" aria-label="Cerrar" onClick={onClose}><X size={22}/></button></div><div className="dialog-content">{editing?<RecordForm resource={resource} row={row} onSaved={onSaved} onCancel={onClose}/>:<><div className="detail-actions">{canEdit&&<button className="primary-button" onClick={onEdit}>Editar registro</button>}<button className="secondary-button" onClick={()=>window.print()}><Printer size={16}/> Imprimir ficha</button></div>{resource==='sources'&&row&&<SourceDetail row={row}/>}<dl className="detail-grid">{config.fields.filter(f=>f.type!=='checklist').map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.resource?display(row?.[`${f.key}_name`]||row?.[`${f.key}_code`]||(row?.[f.key]?`Referencia #${row[f.key]}`:null)):display(row?.[f.key],f.key)}</dd></div>)}</dl>{row?.source_ref?<p className="source-reference"><BookOpen size={16}/>{String(row.source_ref)}</p>:null}{resource==='assets'&&row&&<AssetHistory id={row.id}/>} {resource==='audit'&&<pre className="source-text">{JSON.stringify(row?.detail,null,2)}</pre>}{resource==='work-orders'&&Array.isArray(row?.checklist)&&<div className="checklist-read">{(row.checklist as {label:string;done:boolean}[]).map((c,i)=><p key={i}>{c.done?'✓':'○'} {c.label}</p>)}</div>}</>}</div></dialog>;
}
function SourceDetail({row}:{row:Row}){
 const proposed=row.proposed as {resource?:string;id?:number}|undefined;
 return <div className="source-detail"><p className="alert-info">Compara la transcripción con la imagen original. Los históricos escaneados no se convierten automáticamente en órdenes cerradas.</p>{proposed?.id&&<p className="helper-text">Registro vinculado: {resources[proposed.resource||'']?.title} · ID {proposed.id}. Edita ese registro desde su módulo antes de resolver la revisión.</p>}<a className="secondary-button" href={`/api/source-document/${row.page}/`} target="_blank" rel="noreferrer">Abrir original <ExternalLink size={15}/></a><img className="source-image" src={`/api/source-document/${row.page}/`} alt={`Documento de origen, página ${row.page}`} loading="lazy"/><pre className="source-text">{String(row.raw_text)}</pre></div>;
}
function AssetHistory({id}:{id:number}){
 const [rows,setRows]=useState<Row[]|null>(null),[historic,setHistoric]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{Promise.all([api(`work-orders/?asset=${id}`),api(`historical/?asset=${id}`)]).then(([d,h])=>{setRows(d.results);setHistoric(h.results);}).catch(e=>setError(e.message));},[id]);
 return <section className="asset-history"><h3>Historial de servicios</h3>{error?<ErrorBox message={error}/>:rows===null?<Loading/>:rows.length?rows.map(r=><div className="history-row" key={r.id}><span>OT-{r.id}</span><strong>{display(r.title)}</strong><span>{display(r.scheduled_on)}</span><Badge value={r.status}/></div>):<p className="muted">Sin servicios registrados en la plataforma. Los trabajos anteriores se muestran abajo.</p>}{historic.length>0&&<><h3 style={{marginTop:20}}>Histórico original</h3>{historic.map(r=><div className="history-row" key={r.id}><span>Original #{String(r.legacy_id)}</span><strong>{display(r.description)}</strong><span>{display(r.performed_on)}</span>{r.possible_duplicate_of?<span className="pill warn">Posible repetición</span>:null}</div>)}</>}</section>;
}
const checks=['Limpieza de filtros','Limpieza de evaporadora','Limpieza de condensadora','Revisión de drenaje','Conexiones eléctricas','Prueba de funcionamiento'];
function RecordForm({resource,row,onSaved,onCancel}:{resource:string;row:Row|null;onSaved:()=>void;onCancel:()=>void}){
 const config=resources[resource];const [choices,setChoices]=useState<Record<string,Row[]>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const names=[...new Set(config.fields.map(f=>f.resource).filter(Boolean))] as string[];Promise.all(names.map(async name=>{let page=1,all:Row[]=[];for(;;){const d=await api(`${name}/?page=${page}`);all=all.concat(d.results);if(!d.next)break;page++;}return [name,all] as const;})).then(entries=>{if(active)setChoices(Object.fromEntries(entries));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[config.fields]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget),payload:Record<string,unknown>={};for(const f of config.fields){if(f.type==='checklist'){payload[f.key]=checks.map((label,i)=>({label,done:form.get(`check-${i}`)==='on'}));continue;}const v=form.get(f.key);payload[f.key]=f.type==='checkbox'?v==='on':f.key==='inverter'?(v===''?null:v==='true'):f.resource||f.type==='number'?(v===''?null:Number(v)):f.type==='date'?(v||null):v||'';}try{await api(`${resource}/${row?`${row.id}/`:''}`,{method:row?'PATCH':'POST',body:JSON.stringify(payload)});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const defaultValue=(f:Field)=>{if(row)return row[f.key]===null||row[f.key]===undefined?'':String(row[f.key]);if(f.key==='maintenance_interval_days')return '90';if(f.key==='quantity')return '1';if(f.key==='requested_on'||f.key==='scheduled_on')return today();if(f.key==='criticality'||f.key==='priority')return 'medium';if(f.options&&f.key!=='inverter')return f.options[0][0];return '';};
 if(loading)return <Loading/>;
 return <form onSubmit={submit}><div className="form-grid">{config.fields.map(f=><div className={f.type==='textarea'||f.type==='checklist'?'full-span':''} key={f.key}>{f.type==='checkbox'?<label className="check-label"><input type="checkbox" name={f.key} defaultChecked={Boolean(row?.[f.key])}/>{f.label}</label>:f.type==='checklist'?<fieldset className="checklist"><legend>{f.label}</legend>{checks.map((label,i)=><label key={label}><input type="checkbox" name={`check-${i}`} defaultChecked={Array.isArray(row?.checklist)&&(row.checklist as {label:string;done:boolean}[]).some(c=>c.label===label&&c.done)}/>{label}</label>)}</fieldset>:<><label className="field-label" htmlFor={`f-${f.key}`}>{f.label}{f.required&&<span className="required"> *</span>}</label>{f.resource?<select id={`f-${f.key}`} className="field-input" name={f.key} defaultValue={defaultValue(f)} required={f.required}><option value="">Sin asignar</option>{choices[f.resource]?.map(c=><option key={c.id} value={c.id}>{String(c.code||c.name)}{c.code?` · ${String(c.name||c.brand||c.location_name||'')}`:''}</option>)}</select>:f.options?<select id={`f-${f.key}`} className="field-input" name={f.key} defaultValue={defaultValue(f)}><option value="" disabled={f.key!=='inverter'}>Sin registrar</option>{f.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:f.type==='textarea'?<textarea id={`f-${f.key}`} className="field-input" name={f.key} defaultValue={defaultValue(f)} rows={3} required={f.required}/>:<input id={`f-${f.key}`} className="field-input" name={f.key} type={f.type||'text'} defaultValue={defaultValue(f)} required={f.required} min={f.type==='number'?(f.key==='quantity'||f.key==='maintenance_interval_days'?1:0):undefined} step={f.type==='number'?(f.key==='quantity'||f.key==='maintenance_interval_days'||f.key==='capacity_btu'?1:'0.001'):undefined}/>}</>}</div>)}</div>{resource==='acquisitions'&&<p className="helper-text form-hint">Al recibir la compra, registra sus componentes en Inventario con códigos únicos y vincula la referencia en sus observaciones.</p>}{resource==='work-orders'&&<p className="helper-text form-hint">Para cerrar una orden, indica la fecha de terminación y el trabajo realizado. Un preventivo cerrado actualiza la próxima fecha del equipo; el estado operativo se verifica por separado.</p>}{error&&<ErrorBox message={error}/>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={busy||loading}>{busy?'Guardando…':'Guardar registro'}<Check size={17}/></button></div></form>;
}
function Agenda({user}:{user:User}){
 const [month,setMonth]=useState(today().slice(0,7)),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Row|null>(null),[editing,setEditing]=useState(false),[rev,setRev]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');const [y,m]=month.split('-').map(Number);const end=new Date(y,m,0).getDate();(async()=>{let all:Row[]=[];for(let page=1;;page++){const d=await api(`work-orders/?from=${month}-01&to=${month}-${end}&page=${page}`);all=all.concat(d.results);if(!d.next)break;}if(active)setRows(all.sort((a,b)=>String(a.scheduled_on).localeCompare(String(b.scheduled_on))));})().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month,rev]);
 return <><div className="page-heading"><div><p className="section-eyebrow">MANTENIMIENTO PLANIFICADO</p><h1>Agenda de servicios</h1><p className="muted">Organiza el trabajo antes de que se convierta en una urgencia.</p></div><input className="field-input month-picker" aria-label="Mes de la agenda" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></div><section className="panel">{error?<ErrorBox message={error}/>:loading?<Loading/>:rows.length?<div className="agenda-list">{rows.map(r=><button className="agenda-row" key={r.id} onClick={()=>setSelected(r)}><div className="agenda-date"><strong>{String(r.scheduled_on).slice(-2)}</strong><span>{new Date(`${r.scheduled_on}T12:00:00`).toLocaleDateString('es-MX',{weekday:'short'})}</span></div><div><strong>{display(r.title)}</strong><p>{display(r.asset_code)} · {display(r.location_name)}</p><small>{display(r.technician)}</small></div><Badge value={r.status}/><ChevronRight size={18}/></button>)}</div>:<Empty title="Sin servicios para este mes" description="Crea una orden desde Mantenimiento para incluirla en la agenda."/>}</section>{selected&&<RecordDialog resource="work-orders" row={selected} editing={editing} canEdit={user.role!=='Consulta'&&selected.status!=='completed'} onEdit={()=>setEditing(true)} onClose={()=>{setSelected(null);setEditing(false);}} onSaved={()=>{setSelected(null);setEditing(false);setRev(r=>r+1);}}/>}</>;
}
function Reports(){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[building,setBuilding]=useState(''),[kw,setKw]=useState(''),[hours,setHours]=useState('8'),[days,setDays]=useState('22'),[rate,setRate]=useState('');
 const list=[{kind:'historical',title:'Histórico original',description:'Intervenciones de agosto de 2026 y posibles repeticiones.',icon:History},{kind:'inventory',title:'Inventario general',description:'Componentes, ubicación, modelo y estado actual.',icon:Wind},{kind:'maintenance',title:'Plan de mantenimiento',description:'Vencidos, próximos 30 días y equipos sin programar.',icon:CalendarDays},{kind:'costs',title:'Historial y costos',description:'Órdenes de trabajo, fechas, responsables y costos.',icon:Wrench},{kind:'acquisitions',title:'Control de adquisiciones',description:'Solicitudes, cantidades e inversión registrada.',icon:ShoppingCart},{kind:'warranty',title:'Garantías por vencer',description:'Equipos con garantía que termina en los próximos 60 días.',icon:ShieldCheck},{kind:'quality',title:'Calidad del inventario',description:'Registros por revisar o sin modelo o ubicación.',icon:ClipboardCheck}];
 const estimated=Number(kw)*Number(hours)*Number(days);const valid=Number(kw)>0&&Number(hours)>=0&&Number(hours)<=24&&Number(days)>=0&&Number(days)<=31&&Number(rate)>0;
 const datesValid=!from||!to||from<=to;
 return <><div className="page-heading"><div><p className="section-eyebrow">INFORMACIÓN PARA DECIDIR</p><h1>Reportes y análisis</h1><p className="muted">La información de tu operación, lista para compartir.</p></div><span className="small-tag"><FileBarChart size={15}/> CSV · Excel · PDF</span></div><section className="panel report-filters"><label className="field-label">Desde<input className="field-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field-label">Hasta<input className="field-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="field-label">Edificio<input className="field-input" placeholder="Todos (ej. a, b, c…)" value={building} onChange={e=>setBuilding(e.target.value.toLowerCase())}/></label><p className="helper-text">Las fechas filtran el historial de órdenes. El edificio filtra inventario, mantenimiento, garantías y calidad. Adquisiciones incluye todos los registros.</p></section>{!datesValid&&<ErrorBox message="La fecha inicial debe ser anterior o igual a la final."/>}<div className="report-grid">{list.map(r=><section className="panel report-card" key={r.kind}><div className="report-icon"><r.icon size={24}/></div><h2>{r.title}</h2><p>{r.description}</p><div className="report-downloads">{['csv','xlsx','pdf'].map(format=><a aria-disabled={!datesValid} onClick={e=>{if(!datesValid)e.preventDefault();}} key={format} href={`/api/reports/?${new URLSearchParams({kind:r.kind,format,from,to,building})}`}><Download size={14}/>{format==='xlsx'?'Excel':format.toUpperCase()}</a>)}</div></section>)}</div><section className="panel energy-panel"><div><p className="section-eyebrow">PLANEACIÓN ENERGÉTICA</p><h2>Simula el costo de operación</h2><p className="muted">Estimación con potencia constante. No sustituye mediciones ni considera variaciones de carga o cargos de demanda.</p></div><div className="energy-fields">{[{label:'Potencia total (kW)',value:kw,set:setKw,max:undefined},{label:'Horas al día',value:hours,set:setHours,max:24},{label:'Días al mes',value:days,set:setDays,max:31},{label:'Tarifa (MXN/kWh)',value:rate,set:setRate,max:undefined}].map(f=><label className="field-label" key={f.label}>{f.label}<input className="field-input" type="number" min="0" max={f.max} step="0.01" value={f.value} onChange={e=>f.set(e.target.value)}/></label>)}</div><div className="energy-result"><span>Consumo estimado <strong>{valid?`${estimated.toLocaleString('es-MX')} kWh`:'Completa los datos'}</strong></span><span>Costo estimado <strong>{valid?money(estimated*Number(rate)):'—'}</strong></span></div></section></>;
}

function Account({user}:{user:User}){
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setError('');setMessage('');if(data.get('new_password')!==data.get('confirm')){setError('Las contraseñas nuevas no coinciden.');return;}setBusy(true);try{const r=await api('password/',{method:'POST',body:JSON.stringify({old_password:data.get('old_password'),new_password:data.get('new_password')})});setMessage(r.detail);form.reset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><p className="section-eyebrow">ACCESO PERSONAL</p><h1>Mi cuenta</h1><p className="muted">{user.name} · {user.role}</p></div>{user.can_manage_users&&<a className="secondary-button" href="/admin/auth/user/">Administrar usuarios <ExternalLink size={15}/></a>}</div><section className="panel" style={{maxWidth:600}}><h2>Cambiar contraseña</h2><form className="form-stack" onSubmit={submit}><label className="field-label">Contraseña actual<input className="field-input" name="old_password" type="password" required autoComplete="current-password"/></label><label className="field-label">Nueva contraseña<input className="field-input" name="new_password" type="password" required minLength={8} autoComplete="new-password"/></label><label className="field-label">Repetir nueva contraseña<input className="field-input" name="confirm" type="password" required autoComplete="new-password"/></label>{error&&<ErrorBox message={error}/>} {message&&<p className="alert-success" role="status">{message}</p>}<button className="primary-button" disabled={busy}>{busy?'Actualizando…':'Actualizar contraseña'}</button></form></section></>;
}
