# Generated by Django 5.2.17 on 2026-09-22 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=250)),
                ('needs_review', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('indoor_model', models.CharField(blank=True, max_length=150)),
                ('outdoor_model', models.CharField(blank=True, max_length=150)),
                ('capacity_btu', models.PositiveIntegerField(blank=True, null=True)),
                ('inverter', models.BooleanField(blank=True, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=80)),
                ('refrigerant', models.CharField(blank=True, max_length=40)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('rated_power_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manual_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=250)),
                ('needs_review', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=40)),
                ('resource', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('detail', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('page', models.PositiveIntegerField()),
                ('legacy_id', models.CharField(blank=True, max_length=40)),
                ('raw_text', models.TextField()),
                ('proposed', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('duplicate', 'Duplicado')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('unknown', 'Por verificar'), ('operational', 'Operativo'), ('maintenance', 'En mantenimiento'), ('failed', 'Fuera de servicio'), ('retired', 'Baja')], default='unknown', max_length=20)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_interval_days', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)])),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('criticality', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=250)),
                ('needs_review', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.technicalmodel')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('requested_on', models.DateField()),
                ('expected_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprobada'), ('ordered', 'En compra'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='requested', max_length=20)),
                ('invoice', models.CharField(blank=True, max_length=120)),
                ('justification', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.technicalmodel')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('installation', 'Instalación'), ('inspection', 'Inspección')], default='preventive', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('scheduled', 'Programada'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('scheduled_on', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=180)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('diagnosis', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('source_ref', models.CharField(blank=True, max_length=250)),
                ('needs_review', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.asset')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
