# Generated by Django 5.2.17 on 2026-09-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.PositiveIntegerField(unique=True)),
                ('work_code', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('performed_on', models.DateField()),
                ('recorded_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('possible_duplicate_of', models.PositiveIntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(max_length=250)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_services', to='inventory.asset')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
